### ISSUE TITLE
Cannot submit test results

### ISSUE THREAD

**Issue by DesertsP** [ReXTime/ReXTime#2]
```
{"qid": "anet_val384", "pred_relevant_windows": [[0, 46]], "ans": "C"}
{"qid": "qvh_val521", "pred_relevant_windows": [[20, 56]], "ans": "C"}
{"qid": "anet_val1017", "pred_relevant_windows": [[16, 45]], "ans": "A"}
```
<img width="445" alt="image" src="https://github.com/user-attachments/assets/9f69a157-1245-49b2-8a61-84fc92075d09">

**Comment by DesertsP** [comment]
When I upload a zip file, a new error shows
```
Traceback (most recent call last):
  File "/tmp/codalab/tmpkZpq2s/run/program/evaluate.py", line 289, in 
    acc, gqa, mIoU, r13, r15 = evaluate(truth_filename, submission_answer_filename)
  File "/tmp/codalab/tmpkZpq2s/run/program/evaluate.py", line 249, in evaluate
    submission = load_jsonl(submission_answer_filename)
  File "/tmp/codalab/tmpkZpq2s/run/program/utils.py", line 11, in load_jsonl
    with open(filename, "r") as f:
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/codalab/tmpkZpq2s/run/input/res/pred.jsonl'
```

**Comment by Ayush-00** [comment]
Hi! I am facing the same issue, can you help me with how to evaluate using the submission site?
